name: o
favicon: null
layout_spectrum: 0.8
title: random o-someness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b2b2b2'
    - '#020202'
    - '#8c8784'
    - '#4f4231'
  brandStrength: 0.25
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: a8244b0e-432e-452c-ab83-b03d09bd26ea
    url: null
