name: o
favicon: null
layout_spectrum: 0.32473
title: random o-someness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3c41'
    - '#f3f8f2'
    - '#cbd9da'
    - '#a4adb6'
    - '#627188'
  brandStrength: 0.4375
  lightness: 0.8125
  saturation: 0.75
  rhythmicContrast: 0.5
purpose:
  - name: shares
    item: a8244b0e-432e-452c-ab83-b03d09bd26ea
    url: null
